pipeline {
    agent any
    stages {
        stage('clone github') {
            steps {
                script {
                git branch: 'main', credentialsId: 'jenkins-s3-cred', url: 'https://github.com/shawnnyce1/jenkins_s3.git'
                }
            }
            }
        }


        stage('create S3 Bucket') {
            steps {
                script {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 's3-jenkins', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {

                sh '''
    

                aws s3 mb s3://too-cool-s3 bucket
                sleep 60
                '''
                }

                }
            }
        }


        stage('Delete') {
            steps {
                script {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 's3-jenkins', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh '''
    
                aws s3 rb s3://too-cool-s3 bucket
                '''
                
            }
        }
    }
}
