pipeline {
    agent any // Runs on any available Jenkins agent
    stages {
        stage('clone github repo') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: 'main']], 
                    userRemoteConfigs: [[
                        url: 'https://github.com/shawnnyce1/jenkins_s3.git',
                        credentialsId: 's3-git'
                    ]]
                ])
            }
        }
        stage('Create s3 bucket') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-s3', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh 'aws s3 mb s3://jenkins-aws-s3-bucket'
                    sleep 150
                }
            }
        }
        stage('Delete') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-s3', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh 'aws s3 rb s3://jenkins-aws-s3-bucket'
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}